apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: helloworld
    spec:
      containers:
        - name: nginx-demo
          image: nginx
          ports:
           - name: nginx-port
             containerPort: 3000
