apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: nginx-babitha
    image: nginx
    ports:
    - containerPort: 8080
  - name: docwatcher
    image: afakharany/watcher
    ports:
    - containerPort: 8090 
